version: '3.3'

services:
  app:
    image: php:8.0.2-fpm
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
      - ./php/php.ini:/usr/local/etc/php/conf.d/upload.ini
    depends_on:
      - nginx
  nginx:
    image: nginx:1.19-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysqldb
  mysqldb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql:/var/lib/mysql